### ISSUE TITLE
Generic mode

### ISSUE THREAD

**Issue by dima44** [firsttris/chrome.ipcamviewer#1]
You did what you need! Has studied your github ineterseye things do!
One drawback with this extension is that it does not have the Generic mode. Since a bunch of cameras are now on the SoC HI35XX, it makes no sense to prescribe all the brands. If there is time, please re-select the extension and post Chrome Webstore

**Comment by firsttris** [comment]
i like your idea :+1:  
could go into more detail?
maybe do an example how this generic mode should look like?

**Comment by dima44** [comment]
Snapshot on ip web camera SOC HI3518E_50H10L_S39
ip: http://192.168.1.10/webcapture.jpg?command=snap&channel=1

**Comment by dima44** [comment]
I configured my cameras through export settings in your extension. Further no more settings do not do otherwise the settings overwrite and work will stop))))

**Comment by firsttris** [comment]
ah okay i understood, will add a generic mode where you can just enter the stream url - in the next release

**Comment by firsttris** [comment]
thats already possible as far as i can say:

![image](https://user-images.githubusercontent.com/1709260/62978554-d6e46000-be21-11e9-9a86-7f126c4c3c8a.png)
